### ISSUE TITLE
阻断其他插件消息

### ISSUE THREAD

**Issue by huanxin996** [zhongwen-4/nonebot-plugin-batch-withdrawal#1]
与nonebot-plugin-ncm共同加载时
点歌和下载命令无法使用

插件列表如下（删去此插件后恢复正常）:
plugins = ["nonebot_plugin_treehelp", "nonebot_plugin_analysis_bilibili", "nonebot_plugin_alias", "nonebot_plugin_plus_one", "nonebot_plugin_shindan", "nonebot_plugin_emojimix", "nonebot_plugin_picstatus", "nonebot_plugin_oddtext", "nonebot_plugin_russian_ban", "nonebot-plugin-person", "nonebot-plugin-ncm","nonebot_plugin_update","nonebot_plugin_follow_withdraw","nonebot_plugin_code","nonebot_plugin_zxpix","nonebot_plugin_wordcloud","nonebot_plugin_learning_chat", "nonebot_plugin_hx_yinying"]

python版本3.10
使用napcatQQ

**Comment by zhongwen-4** [comment]
把`LOG_LEVEL=DEBUG`写到env文件里重新触发一下命令然后日志截图我看看

**Comment by huanxin996** [comment]
![Uploading log.png…]()

**Comment by huanxin996** [comment]
![log](https://github.com/user-attachments/assets/dd82135b-6aa2-428f-a0e8-3de30935eafe)

**Comment by zhongwen-4** [comment]
更新了，试一下

**Comment by huanxin996** [comment]
插件已正常响应
谢谢
